// Generates the docker-compose.yml the npm-launched user runs.
//
// Critical difference from the in-repo docker-compose.yml at the
// repo root: this one references PUBLIC images by tag, never
// `build: ./engine`. The npm-launched user has no source checkout.
//
// The image tag matches the npm package's version so `klio@0.1.0`
// always pulls `:0.1.0` of every image. This keeps engine/bridge/
// trust-app/migrations in lockstep — a user who installs an older
// version of the npm package gets the matching engine that knows
// how to roll back schema if needed.

import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const REGISTRY = "ghcr.io/klio-tech";

// Default models. The `openrouter/<vendor>/<model>` format is the
// routing prefix the engine's direct-httpx dispatch uses to pick an
// upstream — the engine's LLM stack consults the leading segment, so
// we encode the provider prefix here at render time rather than in
// engine config. (Pre-0.3.0 this prefix was a LiteLLM convention; the
// engine now reaches OpenRouter natively but the wire shape didn't
// change, so the same prefix keeps working.)
const DEFAULT_EMBEDDING_MODEL = "openrouter/openai/text-embedding-3-small";
const DEFAULT_EXTRACTION_MODEL = "openrouter/anthropic/claude-3-5-haiku";

export type ComposeOptions = {
  /** Image tag to pin every service to. Usually the npm package version. */
  imageTag: string;
  /**
   * JWT signing key shared between engine + trust-app for local-dev
   * auto-login. Generated fresh per install if not provided so two
   * users on the same machine can't accidentally read each other's
   * sessions.
   */
  jwtSigningKey: string;
  /**
   * Embedding model the engine uses by default. Format is
   * `openrouter/<vendor>/<model>` (or `ollama/<model>`,
   * `custom/<model>`) — the engine routes by the leading prefix via
   * direct httpx and reaches OpenRouter using KLIO_OPENROUTER_API_KEY.
   * Defaults to `openrouter/openai/text-embedding-3-small` so a fresh
   * install works against any unmodified OpenRouter account.
   */
  embeddingModel?: string;
  /**
   * Extraction (chat) model the engine uses for fact extraction +
   * recall summarisation. Same prefixed format as `embeddingModel`.
   * Defaults to `openrouter/anthropic/claude-3-5-haiku` — chosen for
   * its balance of cost and quality on short structured outputs.
   */
  extractionModel?: string;
};

/**
 * Returns the absolute path where the npm launcher writes its
 * generated artifacts: ~/.klio/. Flat layout — docker-compose.yml,
 * .env, install.json all live directly here alongside any
 * bridge-side files (e.g. credentials.enc when running outside
 * a container).
 *
 * Created with mode 0700 because it ends up holding secrets
 * (the .env file's JWT signing key + your user/agent UUIDs +
 * any provider API keys you supplied at onboarding).
 *
 * Function name kept as `runtimeDir` for backward compatibility
 * with import sites; the path itself flattened in 0.3.1 from
 * ~/.klio/runtime/ → ~/.klio/ because the extra nesting was
 * confusing — every file there belongs to klio anyway.
 */
export function runtimeDir(): string {
  return join(homedir(), ".klio");
}

/**
 * Materialise the compose file under ~/.klio/runtime/docker-compose.yml.
 * Returns the absolute path so the caller (init command) can pass
 * it to `docker compose -f`.
 */
export function writeComposeFile(opts: ComposeOptions): string {
  const dir = runtimeDir();
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const path = join(dir, "docker-compose.yml");

  const body = renderComposeBody({
    imageTag: opts.imageTag,
    jwtSigningKey: opts.jwtSigningKey,
    embeddingModel: opts.embeddingModel ?? DEFAULT_EMBEDDING_MODEL,
    extractionModel: opts.extractionModel ?? DEFAULT_EXTRACTION_MODEL,
  });
  writeFileSync(path, body, { mode: 0o600 });
  return path;
}

/**
 * Write ~/.klio/runtime/.env so docker compose's automatic env-file
 * pickup just works. Used both by the trust-app service (which reads
 * KLIO_LOCAL_USER_ID / KLIO_LOCAL_AGENT_ID for auto-login) and by
 * humans running `docker compose -f ~/.klio/runtime/docker-compose.yml ps`
 * directly.
 *
 * Mode 0600 — this file holds your refresh token's JWT signing key
 * AND your model-provider credentials (OpenRouter or Custom API key),
 * both of which a hostile coresident user shouldn't be able to read.
 */
export function writeEnvFile(env: Record<string, string>): string {
  const dir = runtimeDir();
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const path = join(dir, ".env");

  const lines = [
    "# Generated by klio init — do not commit.",
    "# Holds the local-dev JWT key, your model-provider credentials",
    "# (KLIO_OPENROUTER_API_KEY or KLIO_CUSTOM_API_KEY), and your",
    "# user/agent UUIDs so trust-app can auto-login. Re-run",
    "# `npx @klio-tech/klio init` to refresh.",
    "",
  ];
  for (const [k, v] of Object.entries(env)) {
    lines.push(`${k}=${v}`);
  }
  writeFileSync(path, lines.join("\n") + "\n", { mode: 0o600 });
  return path;
}

/**
 * Ensure parent directory of `path` exists with mode 0700. Used for
 * the credentials file and other secret-bearing artifacts the npm
 * launcher creates.
 */
export function ensureDir(path: string): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
}

export type ComposeBodyOptions = {
  imageTag: string;
  jwtSigningKey: string;
  embeddingModel: string;
  extractionModel: string;
};

// Note: KLIO_EMBEDDING_DIM is interpolated at compose-up time from
// the sibling `.env` file (see `writeEnvFile` / `buildEnvVars`), not
// rendered into the YAML body. This mirrors how every other secret /
// per-install value is plumbed — keeping the YAML body identical
// across users so it's safe to cache, diff, and reason about.

/**
 * Pure function that returns the compose YAML body as a string. All
 * secrets are interpolated from env vars (`${VAR}`) so the same body
 * is reused regardless of which OpenRouter key the user supplied —
 * the key lives only in the sibling `.env` file.
 *
 * Exported so tests can assert on the rendered body without writing
 * to disk; callers in production should prefer `writeComposeFile`.
 */
export function renderComposeBody(opts: ComposeBodyOptions): string {
  const tag = opts.imageTag;
  const embedModel = opts.embeddingModel;
  const extractModel = opts.extractionModel;

  // Indentation matters in YAML — keep it at 2 spaces throughout.
  // The file is rendered as a string literal rather than via a yaml
  // library to keep the npm package's runtime closure empty.
  return `# Generated by @klio-tech/klio v${tag} — do not edit by hand.
# Re-run \`npx @klio-tech/klio init\` to regenerate this file with
# updated image tags. Local edits will be overwritten.
#
# What this brings up:
#   postgres   — pgvector for memory storage
#   redis      — pub/sub for cross-agent realtime + caches
#   engine     — FastAPI REST API + audit chain
#   bridge     — Go daemon + MCP shim (klio hook / klio-mcp targets)
#   trust-app  — Next.js dashboard at http://127.0.0.1:3000

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: klio-postgres
    environment:
      POSTGRES_USER: klio
      POSTGRES_PASSWORD: klio_dev_password
      POSTGRES_DB: klio
    volumes:
      - klio-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klio -d klio"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: klio-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - klio-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  engine:
    image: ${REGISTRY}/klio-engine:${tag}
    container_name: klio-engine
    pull_policy: missing
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      KLIO_DATABASE_URL: postgresql+asyncpg://klio:klio_dev_password@postgres:5432/klio
      KLIO_REDIS_URL: redis://redis:6379/0
      KLIO_JWT_SIGNING_KEY: \${KLIO_JWT_SIGNING_KEY}
      # Engine reads this via the openrouter_api_key config field and
      # talks to https://openrouter.ai/api/v1 directly via httpx —
      # the LiteLLM-era \`OPENROUTER_API_KEY\` pass-through env var was
      # dropped in 0.3.0 alongside the LiteLLM dependency.
      KLIO_OPENROUTER_API_KEY: \${KLIO_OPENROUTER_API_KEY}
      # Custom OpenAI-compatible endpoint (e.g. self-hosted LiteLLM
      # proxy, Azure OpenAI, vLLM, Together, Groq). Both vars are
      # blank when the user picked OpenRouter or Ollama; the engine's
      # \`custom/<model>\` router only consults them when a model name
      # carries the matching prefix.
      KLIO_CUSTOM_BASE_URL: \${KLIO_CUSTOM_BASE_URL}
      KLIO_CUSTOM_API_KEY: \${KLIO_CUSTOM_API_KEY}
      KLIO_EMBEDDING_MODEL: ${embedModel}
      KLIO_EXTRACTION_MODEL: ${extractModel}
      # Reach the host's native Ollama daemon from inside the engine
      # container. The default targets the host gateway (Docker
      # Desktop on macOS / Windows resolves it automatically; the
      # extra_hosts entry below maps it to host-gateway on Linux).
      # Override via \`~/.klio/.env\` if Ollama runs on a non-default
      # port or a different host. The engine ignores this var when
      # the picked provider is OpenRouter or Custom because dispatch
      # routes by model-name prefix, not by env presence — but
      # leaving it set is harmless.
      KLIO_OLLAMA_API_BASE: \${KLIO_OLLAMA_API_BASE:-http://host.docker.internal:11434}
      # Native output dim of the chosen embedding model. Only used
      # for non-registry models (custom/* and escape-hatch openrouter/*
      # the engine doesn't know natively); the npm probe reads it back
      # from the provider during onboarding. Blank when the user picked
      # a registry-known model — the engine resolves the dim from its
      # static EMBEDDING_MODELS table in that case.
      KLIO_EMBEDDING_DIM: \${KLIO_EMBEDDING_DIM}
      # Memory curator — Phase 6 of \`klio init\` writes these into
      # ~/.klio/.env. The defaults (\`:-true\`, \`:-3600\`, \`:-\`) keep
      # the engine sensible even when an older install's env file
      # predates Phase 6 (curator on, hourly cadence, falls back to
      # the extraction model). Run \`klio update curator\` to change.
      KLIO_CURATOR_ENABLED: \${KLIO_CURATOR_ENABLED:-true}
      KLIO_CURATOR_INTERVAL_SECS: \${KLIO_CURATOR_INTERVAL_SECS:-3600}
      KLIO_CURATOR_MODEL: \${KLIO_CURATOR_MODEL:-}
      KLIO_DEV_KMS_PATH: /var/lib/klio/dev-kms.key
      KLIO_LOG_LEVEL: \${KLIO_LOG_LEVEL:-INFO}
    volumes:
      - klio-engine-data:/var/lib/klio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "python -c \\"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).status==200 else 1)\\""]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  bridge:
    image: ${REGISTRY}/klio-bridge:${tag}
    container_name: klio-bridge
    pull_policy: missing
    depends_on:
      engine:
        condition: service_healthy
    environment:
      KLIO_API_URL: http://engine:8000
      KLIO_REDIS_URL: redis://redis:6379/0
      KLIO_LOG_LEVEL: \${KLIO_LOG_LEVEL:-INFO}
    volumes:
      - klio-bridge-data:/data
      # ~/.claude is read-only because the daemon only walks session
      # JSONL files for backfill — no writes to host config.
      - \${HOME}/.claude:/host/.claude:ro
      # NEW v0.6.0 — bridge writes ~/.klio/update-state.json from the
      # auto-updater ticker (~/.klio is the host's klio runtime dir,
      # already used for the compose file and .env). Engine + trust-app
      # read the same file via the same mount.
      - \${HOME}/.klio:/host/.klio:rw
    restart: unless-stopped

  trust-app:
    image: ${REGISTRY}/klio-trust-app:${tag}
    container_name: klio-trust-app
    pull_policy: missing
    depends_on:
      engine:
        condition: service_healthy
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      KLIO_ENGINE_URL: http://engine:8000
      KLIO_JWT_SIGNING_KEY: \${KLIO_JWT_SIGNING_KEY}
      KLIO_LOCAL_DEV: "1"
      KLIO_LOCAL_USER_ID: \${KLIO_LOCAL_USER_ID}
      KLIO_LOCAL_AGENT_ID: \${KLIO_LOCAL_AGENT_ID}
    volumes:
      # NEW v0.6.0 — read-only mount of ~/.klio so the dashboard's
      # server-side handler can read update-state.json for the
      # update-status surface.
      - \${HOME}/.klio:/host/.klio:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  klio-postgres-data:
  klio-redis-data:
  klio-engine-data:
  klio-bridge-data:
`;
}
