/**
 * Helpers for reading and surgically updating ~/.klio/.env without
 * blowing away unrelated sections.
 *
 * The file is line-oriented: comments start with `#`, key=value
 * pairs use the first `=` as the separator, blank lines are
 * ignored. We DO NOT do dotenv-style quote-stripping — docker
 * compose accepts the value verbatim, and the npm CLI never writes
 * quoted values, so a value like `"foo"` is preserved with the
 * quotes intact.
 *
 * Why a separate module from `compose.ts:writeEnvFile`:
 *   - `writeEnvFile` rewrites the entire env from a Record<string,
 *     string> the caller has already assembled — it's the WRITE side
 *     used by `klio init` after it has collected every value.
 *   - `parseEnvFile` + `mergeEnvFile` here are the READ + targeted-
 *     REPLACE side used by `klio update curator` / `klio update
 *     provider`, which only touch a subset of keys and must preserve
 *     everything else (JWT key, user/agent UUIDs, OpenRouter creds).
 *
 * Both modules share the same on-disk format, so a file written by
 * either path is readable by the other.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname } from "node:path";


/**
 * Parse a .env file into a flat key→value map. Returns an empty
 * object when the file does not exist — the update flows treat a
 * missing env file as "no prior state, all defaults" rather than as
 * an error condition. (klio init creates the file, so absence here
 * means a partially-removed install or a fresh machine running
 * `klio update` before `klio init` — both rare, neither worth
 * crashing on.)
 *
 * The first `=` in a line is the key/value separator. Subsequent
 * `=` characters are part of the value. Empty keys are skipped.
 */
export function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const content = readFileSync(path, "utf8");
  const out: Record<string, string> = {};
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1);
    if (key !== "") out[key] = value;
  }
  return out;
}


/**
 * Merge `updates` into the env file at `path`, preserving every key
 * that isn't in `updates`. Creates the file (and parent directory,
 * mode 0700) if missing.
 *
 * The output preserves the parsed key order plus appends any keys
 * from `updates` that didn't exist before. Comments and blank lines
 * from the original file are NOT preserved — this is a regenerated
 * file, with a single header comment block at the top.
 *
 * File mode is 0600 because the env file holds the JWT signing key,
 * provider API credentials, and user/agent UUIDs — same threat model
 * as `compose.ts:writeEnvFile`.
 */
export function mergeEnvFile(
  path: string,
  updates: Record<string, string>,
): void {
  const existing = parseEnvFile(path);
  // Object spread preserves the existing order for unchanged keys
  // and overwrites in place where `updates` collides; new keys land
  // at the end. This matches the original file's layout for any
  // unaltered keys, which makes diffs minimal across re-runs.
  const merged: Record<string, string> = { ...existing, ...updates };

  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const lines = [
    "# Generated by klio — do not commit.",
    "# Holds the local-dev JWT key, provider credentials, curator",
    "# settings, and user/agent UUIDs. Re-run `klio update` to",
    "# refresh a slice without losing the rest.",
    "",
  ];
  for (const [k, v] of Object.entries(merged)) {
    lines.push(`${k}=${v}`);
  }
  writeFileSync(path, lines.join("\n") + "\n", { mode: 0o600 });
}
