"""Header handling for a transparent forwarding proxy.

The contract this module implements: **the agent must not be able to
tell the proxy is there.** Every header the client sent reaches the
upstream, and every header the upstream returned reaches the client,
with the single class of exception below.

Hop-by-hop headers
------------------
Per RFC 9110 §7.6.1, a small set of headers describe *this* TCP
connection rather than the message being carried, and a proxy must not
blindly forward them. Forwarding ``Transfer-Encoding: chunked`` from
upstream while our own ASGI server re-frames the body produces a body
that is chunk-encoded twice; forwarding ``Connection: close`` closes a
connection the client is still using. So they are dropped on both legs
and regenerated by whichever server is actually terminating that hop.

Everything else — including ``anthropic-ratelimit-*``,
``retry-after``, ``request-id``, ``anthropic-organization-id`` and any
header Anthropic adds tomorrow that we have never heard of — is
forwarded verbatim. This module works from a *deny* list, never an
allow list, precisely so a header we do not know about survives.

Content encoding
----------------
``Content-Encoding`` and ``Content-Length`` are NOT stripped. The
response leg reads the upstream body with ``aiter_raw()``, which yields
the bytes exactly as they arrived off the wire, still compressed if the
upstream compressed them. Forwarding the encoding headers alongside
those bytes is therefore correct, and the client decompresses as it
would have done talking to Anthropic directly. Stripping them (or
letting httpx transparently decode) is how a "transparent" proxy ends
up handing clients gzip bytes labelled as plain text.
"""

from __future__ import annotations

from collections.abc import Iterable

#: Headers that describe a single transport connection rather than the
#: message. Dropped on both request and response legs. Lowercase — HTTP
#: header names are case-insensitive and both httpx and Starlette
#: normalise to lowercase, so comparisons here are too.
HOP_BY_HOP_HEADERS: frozenset[str] = frozenset(
    {
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "proxy-connection",  # non-standard but widely emitted
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    }
)

#: Request headers we must not forward as-is because they name *this*
#: hop rather than the upstream.
#:
#: ``host`` — the client sent ``localhost:8787``; the upstream needs its
#: own authority, and for TLS it must match the certificate. httpx
#: derives the correct value from the target URL when we omit it.
#:
#: ``content-length`` — recomputed by httpx from the body we hand it.
#: In stage 3 the body is byte-identical so the number would match
#: anyway, but the compression seam exists to change that body later,
#: and a stale content-length is a silently truncated request.
_REQUEST_ONLY_DROPS: frozenset[str] = frozenset({"host", "content-length"})


def forwardable_request_headers(
    headers: Iterable[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Filter client request headers down to what may go upstream.

    Order and duplicates are preserved: some headers (``cookie``,
    ``accept``) are order-significant to a picky server, and collapsing
    duplicates is a behaviour change we have no reason to make.
    """
    out: list[tuple[str, str]] = []
    for name, value in headers:
        lowered = name.lower()
        if lowered in HOP_BY_HOP_HEADERS or lowered in _REQUEST_ONLY_DROPS:
            continue
        out.append((name, value))
    return out


def forwardable_response_headers(
    headers: Iterable[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Filter upstream response headers down to what may go to the client.

    Only hop-by-hop headers are removed. ``content-length`` is kept:
    unlike the request leg we forward the upstream body byte for byte,
    so the upstream's own length is the true length. Dropping it would
    force our server into chunked framing for responses the client was
    told to expect as fixed-length.
    """
    return [(name, value) for name, value in headers if name.lower() not in HOP_BY_HOP_HEADERS]


def ensure_no_transparent_decoding(
    headers: list[tuple[str, str]],
) -> list[tuple[str, str]]:
    """Pin ``accept-encoding`` when the client did not send one.

    httpx injects a default ``Accept-Encoding: gzip, deflate`` (plus
    ``br``/``zstd`` when the optional codecs are installed) on any
    request that lacks the header. That default is httpx's preference,
    not the client's — and because we forward the response body raw, a
    client that never asked for compression would receive compressed
    bytes it does not know to decode.

    Sending ``identity`` in that case asks the upstream for exactly what
    such a client can handle. Clients that *did* send an
    ``accept-encoding`` are untouched and keep negotiating for
    themselves.

    Claude Code and Codex both send the header, so in practice this is a
    guard for hand-rolled clients and for our own tests — but it is the
    difference between "transparent" and "transparent for the two
    clients we tried".
    """
    if any(name.lower() == "accept-encoding" for name, _ in headers):
        return headers
    return [*headers, ("accept-encoding", "identity")]
