package bootstrap

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// LocalDevEnvOptions configures WriteLocalDevEnv.
type LocalDevEnvOptions struct {
	// UserID is the user_id minted at provisioning. Required.
	UserID string

	// AgentID is the agent_id minted at provisioning. Required.
	AgentID string

	// JWTSigningKey is the shared HMAC secret used by the engine and
	// by the trust-app to sign + verify session tokens. Empty falls
	// back to "dev-secret" so a user who never set KLIO_JWT_SIGNING_KEY
	// still gets a working setup; production deployments override.
	JWTSigningKey string

	// GlobalPath overrides the location of the per-user dotenv file.
	// Empty defaults to ~/.klio/local-dev.env. Tests use this to
	// point at a tempdir.
	GlobalPath string

	// ProjectRoot is an optional repo root containing a
	// docker-compose.yml that references the trust-app service.
	// If non-empty, WriteLocalDevEnv ALSO writes <ProjectRoot>/.env
	// so docker-compose's default env-file pickup just works without
	// any further symlinks or copies. Computed via FindKlioProjectRoot
	// from the user's cwd in the runInit caller.
	ProjectRoot string
}

// WriteLocalDevEnv writes a dotenv file with the credentials needed
// for the trust-app docker service to auto-login as this user.
//
// Always writes to opts.GlobalPath (default ~/.klio/local-dev.env)
// with mode 0600 so the file is readable only by this user — it
// holds a JWT signing key and the user's own ID, both effectively
// session-bearer secrets.
//
// Additionally writes <ProjectRoot>/.env when ProjectRoot is set,
// for docker-compose's automatic pickup. The project-root .env file
// is also 0600.
//
// Returns the list of paths written so the caller can print them.
// Idempotent: contents are deterministic from (UserID, AgentID,
// JWTSigningKey), so re-running with the same inputs is a no-op
// from the user's point of view.
func WriteLocalDevEnv(opts LocalDevEnvOptions) ([]string, error) {
	if opts.UserID == "" {
		return nil, errors.New("WriteLocalDevEnv: UserID required")
	}
	if opts.AgentID == "" {
		return nil, errors.New("WriteLocalDevEnv: AgentID required")
	}

	body := buildLocalDevEnvBody(opts)
	written := []string{}

	globalPath := opts.GlobalPath
	if globalPath == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("home dir: %w", err)
		}
		globalPath = filepath.Join(home, ".klio", "local-dev.env")
	}
	if err := writeDotenv(globalPath, body); err != nil {
		return written, fmt.Errorf("write %s: %w", globalPath, err)
	}
	written = append(written, globalPath)

	if opts.ProjectRoot != "" {
		projectPath := filepath.Join(opts.ProjectRoot, ".env")
		if err := writeDotenv(projectPath, body); err != nil {
			return written, fmt.Errorf("write %s: %w", projectPath, err)
		}
		written = append(written, projectPath)
	}

	return written, nil
}

// FindKlioProjectRoot walks up from start looking for a directory
// containing a docker-compose.yml that mentions the trust-app
// service. Returns "" when no match is found within 8 levels (a
// generous limit that still avoids accidental matches on a system-
// wide compose file).
func FindKlioProjectRoot(start string) string {
	if start == "" {
		return ""
	}
	cur := start
	for i := 0; i < 8; i++ {
		for _, name := range []string{"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"} {
			path := filepath.Join(cur, name)
			data, err := os.ReadFile(path)
			if err != nil {
				continue
			}
			// Cheap heuristic: the service block mentions trust-app.
			// We don't parse YAML to keep the dependency footprint
			// minimal and avoid edge cases with unusual compose layouts.
			if strings.Contains(string(data), "trust-app") {
				return cur
			}
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			break
		}
		cur = parent
	}
	return ""
}

func buildLocalDevEnvBody(opts LocalDevEnvOptions) string {
	key := opts.JWTSigningKey
	if key == "" {
		key = "dev-secret"
	}
	return fmt.Sprintf(`# Generated by klio init — do NOT commit.
#
# Used by docker-compose's trust-app service to auto-login as you, so
# you can browse memories at http://127.0.0.1:3000 without juggling
# magic-link emails on your own machine.
#
# To rotate any of these (e.g. after re-init), re-run klio init.

KLIO_JWT_SIGNING_KEY=%s
KLIO_LOCAL_USER_ID=%s
KLIO_LOCAL_AGENT_ID=%s
`, key, opts.UserID, opts.AgentID)
}

func writeDotenv(path, body string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	// O_CREATE|O_TRUNC|O_WRONLY with 0600 — overwrite atomically with
	// owner-only perms. We don't use O_EXCL because re-running klio
	// init must be allowed to refresh the file (e.g. JWT key changed).
	//
	// IMPORTANT: the perm arg to OpenFile is only honored when the
	// file is *created*. If the file already exists (with looser
	// perms — e.g. 0644 from a hand-rolled `cat > .env`), the
	// existing mode is preserved. We Chmod explicitly after writing
	// to enforce 0600 regardless of prior state.
	f, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	if _, err := f.WriteString(body); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Chmod(path, 0o600)
}
