// Keep the proxy alive across crashes and reboots.
//
// This is not a nice-to-have. Once ANTHROPIC_BASE_URL points at
// localhost:8787, a dead proxy does not degrade the agent — the agent
// cannot reach a model at all. That is strictly worse than having no
// compression, so the wiring is only defensible if something restarts
// the proxy without the user knowing it stopped.
//
// TWO LAYERS, because each covers what the other cannot:
//
//   1. Docker's `restart: unless-stopped` on the proxy service. Handles
//      a crashed container and a restarted Docker daemon.
//   2. A host-side supervisor unit (launchd / systemd / Task Scheduler)
//      that runs `klio proxy ensure`. Handles the case Docker cannot
//      handle by definition: the Docker daemon itself not running after
//      a reboot. On macOS especially, Docker Desktop does not always
//      start at login, and `restart: unless-stopped` is a promise the
//      daemon can only keep while it is alive.
//
// The unit runs a CHECK, not the proxy itself. `klio proxy ensure`
// probes /__klio/health and only calls `docker compose up -d proxy`
// when the probe fails. That keeps the supervisor's job idempotent and
// cheap, and means the unit does not need to encode anything about how
// the proxy is run — if the stack later moves off Docker, only `ensure`
// changes.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join } from "node:path";

import { PROXY_HEALTH_PATH, PROXY_PROBE_URL, type ProxyHealth } from "./constants.js";

/** Reverse-DNS label — launchd's convention, and the plist's filename. */
export const LAUNCHD_LABEL = "tech.klio.proxy";

/** systemd unit name. `.service`, not `.timer`: the check is periodic
 * via an accompanying timer, but the unit itself is a one-shot check. */
export const SYSTEMD_UNIT = "klio-proxy.service";
export const SYSTEMD_TIMER = "klio-proxy.timer";

/** How often the supervisor re-checks that the proxy is answering. */
export const CHECK_INTERVAL_SECONDS = 60;

export type SupervisorKind = "launchd" | "systemd" | "windows" | "unsupported";

export function detectSupervisor(osPlatform = platform()): SupervisorKind {
  switch (osPlatform) {
    case "darwin":
      return "launchd";
    case "linux":
      return "systemd";
    case "win32":
      return "windows";
    default:
      return "unsupported";
  }
}

export type SupervisorPaths = {
  launchAgent: string;
  systemdUnit: string;
  systemdTimer: string;
};

export function supervisorPaths(home = homedir()): SupervisorPaths {
  return {
    launchAgent: join(home, "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`),
    systemdUnit: join(home, ".config", "systemd", "user", SYSTEMD_UNIT),
    systemdTimer: join(home, ".config", "systemd", "user", SYSTEMD_TIMER),
  };
}

/**
 * launchd agent.
 *
 * `KeepAlive` is a dictionary rather than `true`. Plain `KeepAlive:
 * true` means "restart whenever this exits", which for a command that
 * exits 0 after a successful check produces a tight respawn loop —
 * launchd throttles it to every 10 seconds and fills the system log
 * with complaints. `SuccessfulExit: false` restarts only on FAILURE,
 * and `StartInterval` drives the routine re-check.
 *
 * `RunAtLoad` is what actually covers the reboot case: it fires the
 * check at login, when Docker Desktop may still be starting or may not
 * be configured to start at all.
 */
export function renderLaunchAgent(klioCommand: string[]): string {
  const args = klioCommand
    .map((a) => `    <string>${escapeXml(a)}</string>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by \`klio init\` — keeps the Klio compression proxy reachable.

  Once ANTHROPIC_BASE_URL points at localhost, a dead proxy means your
  coding agent cannot reach a model at all. This agent re-checks every
  ${CHECK_INTERVAL_SECONDS}s and at login, and brings the proxy back if it is not answering.

  Remove with \`klio uninit\`, or:
    launchctl bootout gui/$(id -u)/${LAUNCHD_LABEL}
    rm ~/Library/LaunchAgents/${LAUNCHD_LABEL}.plist
-->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StartInterval</key>
  <integer>${CHECK_INTERVAL_SECONDS}</integer>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${escapeXml(join(homedir(), ".klio", "proxy-supervisor.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(homedir(), ".klio", "proxy-supervisor.log"))}</string>
</dict>
</plist>
`;
}

/**
 * systemd user service + timer.
 *
 * `Restart=always` on a `Type=oneshot` unit is a contradiction systemd
 * rejects, so the periodic behaviour lives in the timer and the unit
 * carries `Restart=on-failure` with a short backoff for the case where
 * the check itself fails transiently (Docker socket not up yet).
 *
 * The timer's `Persistent=true` covers the reboot case: if the machine
 * was off when a check was due, it runs immediately on boot.
 */
export function renderSystemdUnit(klioCommand: string[]): string {
  return `# Generated by \`klio init\` — keeps the Klio compression proxy reachable.
#
# Once ANTHROPIC_BASE_URL points at localhost, a dead proxy means your
# coding agent cannot reach a model at all. This unit checks that the
# proxy is answering and restarts it if not.
#
# Remove with \`klio uninit\`.

[Unit]
Description=Klio compression proxy health check
# The check needs Docker. Ordering only — systemd user units cannot
# depend on a system unit, so this is advisory and the check itself
# tolerates a Docker daemon that is not up yet.
After=network-online.target

[Service]
Type=oneshot
ExecStart=${klioCommand.map(shellQuote).join(" ")}
# The check is expected to succeed and exit. Retry a few times on
# failure with a short backoff — a Docker daemon that is still starting
# is the common transient cause.
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=default.target
`;
}

export function renderSystemdTimer(): string {
  return `# Generated by \`klio init\` — drives the periodic proxy health check.
#
# Remove with \`klio uninit\`.

[Unit]
Description=Periodic Klio compression proxy health check
Requires=${SYSTEMD_UNIT}

[Timer]
# Fire shortly after boot, then every ${CHECK_INTERVAL_SECONDS}s.
OnBootSec=30s
OnUnitActiveSec=${CHECK_INTERVAL_SECONDS}s
# If the machine was off when a check was due, run it on boot rather
# than waiting for the next interval — the reboot case is exactly the
# one Docker's own restart policy cannot cover.
Persistent=true
Unit=${SYSTEMD_UNIT}

[Install]
WantedBy=timers.target
`;
}

export type InstallResult = {
  kind: SupervisorKind;
  installed: boolean;
  /** Paths written, for init's output and for uninit. */
  paths: string[];
  /** Human-readable outcome, including "why not" when not installed. */
  detail: string;
};

/**
 * Write and load the platform supervisor.
 *
 * Never throws. A supervisor that fails to install is a real
 * degradation — the proxy will not come back after a reboot — but it
 * must not abort `klio init`, because the proxy itself is running and
 * the user's agent works right now. The failure is reported so `klio
 * doctor` and the user can act on it.
 */
export async function installSupervisor(
  klioCommand: string[],
  opts: { platform?: NodeJS.Platform; paths?: SupervisorPaths } = {},
): Promise<InstallResult> {
  const kind = detectSupervisor(opts.platform ?? platform());
  const paths = opts.paths ?? supervisorPaths();

  try {
    switch (kind) {
      case "launchd": {
        writeUnit(paths.launchAgent, renderLaunchAgent(klioCommand));
        // bootout first so a re-run reloads the new plist rather than
        // erroring with "service already loaded". Failure is expected
        // and ignored on a first install.
        await run("launchctl", ["bootout", `gui/${process.getuid?.() ?? 0}/${LAUNCHD_LABEL}`]);
        const loaded = await run("launchctl", [
          "bootstrap",
          `gui/${process.getuid?.() ?? 0}`,
          paths.launchAgent,
        ]);
        return {
          kind,
          installed: loaded.code === 0,
          paths: [paths.launchAgent],
          detail:
            loaded.code === 0
              ? `launchd agent ${LAUNCHD_LABEL} loaded (checks every ${CHECK_INTERVAL_SECONDS}s and at login)`
              : `plist written but launchctl bootstrap failed: ${loaded.stderr.trim() || "unknown error"}. ` +
                `The proxy is running now but will not restart after a reboot.`,
        };
      }

      case "systemd": {
        writeUnit(paths.systemdUnit, renderSystemdUnit(klioCommand));
        writeUnit(paths.systemdTimer, renderSystemdTimer());
        await run("systemctl", ["--user", "daemon-reload"]);
        const enabled = await run("systemctl", ["--user", "enable", "--now", SYSTEMD_TIMER]);
        return {
          kind,
          installed: enabled.code === 0,
          paths: [paths.systemdUnit, paths.systemdTimer],
          detail:
            enabled.code === 0
              ? `systemd user timer ${SYSTEMD_TIMER} enabled (checks every ${CHECK_INTERVAL_SECONDS}s)`
              : `units written but systemctl enable failed: ${enabled.stderr.trim() || "unknown error"}. ` +
                `If this is a headless box, \`loginctl enable-linger $USER\` lets user timers run without an active session.`,
        };
      }

      case "windows":
        // Documented, not implemented. Task Scheduler is driven through
        // schtasks.exe with an XML definition, and shipping that without
        // a Windows machine to verify it on would be worse than saying
        // plainly that it is not done: a supervisor that silently fails
        // to install is indistinguishable from one that works, right up
        // until the first reboot.
        return {
          kind,
          installed: false,
          paths: [],
          detail:
            "Windows supervision is not installed automatically yet. Docker Desktop's " +
            "`restart: unless-stopped` covers crashes; to cover reboots, enable " +
            '"Start Docker Desktop when you sign in" in Docker Desktop settings.',
        };

      default:
        return {
          kind,
          installed: false,
          paths: [],
          detail: `no supervisor for platform ${opts.platform ?? platform()}; the proxy will not restart after a reboot`,
        };
    }
  } catch (err) {
    return {
      kind,
      installed: false,
      paths: [],
      detail: `supervisor install failed: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/** Unload and delete the supervisor units. Never throws. */
export async function uninstallSupervisor(
  opts: { platform?: NodeJS.Platform; paths?: SupervisorPaths } = {},
): Promise<InstallResult> {
  const kind = detectSupervisor(opts.platform ?? platform());
  const paths = opts.paths ?? supervisorPaths();
  const removed: string[] = [];

  try {
    if (kind === "launchd") {
      await run("launchctl", ["bootout", `gui/${process.getuid?.() ?? 0}/${LAUNCHD_LABEL}`]);
      removed.push(...removeIfPresent([paths.launchAgent]));
    } else if (kind === "systemd") {
      await run("systemctl", ["--user", "disable", "--now", SYSTEMD_TIMER]);
      removed.push(...removeIfPresent([paths.systemdTimer, paths.systemdUnit]));
      await run("systemctl", ["--user", "daemon-reload"]);
    }
    return {
      kind,
      installed: false,
      paths: removed,
      detail: removed.length > 0 ? `removed ${removed.length} unit file(s)` : "nothing to remove",
    };
  } catch (err) {
    return {
      kind,
      installed: false,
      paths: removed,
      detail: `supervisor removal failed: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/**
 * What a health probe learned. `health` is present only when something
 * answered `{ "status": "ok" }`, and is deliberately PARTIAL: the
 * responder may be an older Klio proxy, the Python container, or some
 * unrelated listener that happens to serve that shape, so every field
 * has to be treated as absent until checked.
 */
export type ProbeResult = {
  alive: boolean;
  detail: string;
  health?: Partial<ProxyHealth>;
};

/**
 * Is the proxy answering?
 *
 * Deliberately dials the IPv4 literal rather than `localhost`: Docker
 * publishes the port on 127.0.0.1 only, so on a host that resolves
 * `localhost` to `::1` first, a check against `localhost` would report
 * the proxy dead while it is happily serving every client that falls
 * back to IPv4.
 */
export async function probeProxy(
  timeoutMs = 3000,
  url = `${PROXY_PROBE_URL}${PROXY_HEALTH_PATH}`,
): Promise<ProbeResult> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, { signal: controller.signal });
    if (!response.ok) {
      return { alive: false, detail: `health endpoint returned ${response.status}` };
    }
    const body = (await response.json()) as Partial<ProxyHealth> | null;
    const alive = body?.status === "ok";
    return {
      alive,
      detail: alive ? `alive (${body?.mode ?? "unknown mode"})` : "unhealthy",
      // Handed back verbatim (and only when the responder is healthy) so
      // callers that need to know WHICH proxy answered — `klio proxy
      // stop` before it signals anything, `klio init` checking for a
      // survivor holding stale credentials — do not have to re-probe and
      // race with whatever changed in between.
      health: alive ? (body as Partial<ProxyHealth>) : undefined,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      alive: false,
      detail: message.includes("abort") ? `no response within ${timeoutMs}ms` : message,
    };
  } finally {
    clearTimeout(timer);
  }
}

// ---- internals --------------------------------------------------------

function writeUnit(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o755 });
  writeFileSync(path, body, { mode: 0o644 });
}

function removeIfPresent(paths: string[]): string[] {
  const removed: string[] = [];
  for (const p of paths) {
    if (!existsSync(p)) continue;
    try {
      unlinkSync(p);
      removed.push(p);
    } catch {
      /* best effort — reported via the count, not fatal */
    }
  }
  return removed;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Quote for a systemd `ExecStart` line. systemd's parser understands
 * double-quoted arguments with backslash escapes; anything without
 * whitespace or quotes is left bare so the generated unit stays
 * readable.
 */
function shellQuote(arg: string): string {
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(arg)) return arg;
  return `"${arg.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function run(
  cmd: string,
  args: string[],
): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (c) => (stdout += c.toString()));
    child.stderr.on("data", (c) => (stderr += c.toString()));
    // 127 mirrors the shell's "command not found" so callers can tell a
    // missing launchctl/systemctl from one that ran and refused.
    child.on("error", () => resolve({ code: 127, stdout, stderr }));
    child.on("exit", (code) => resolve({ code: code ?? 0, stdout, stderr }));
  });
}

/**
 * The command the supervisor should run every minute.
 *
 * This is fiddlier than it looks. The obvious answer —
 * `[process.execPath, process.argv[1], "proxy", "ensure"]` — is right
 * for a normal install but wrong for the primary onboarding path, which
 * is `npx @klio-tech/klio init`. npx unpacks the package into a cache
 * directory under `_npx/<hash>/`, and that directory is garbage
 * collected. A launchd plist pointing into it works today and silently
 * stops working whenever npm decides to clean up — leaving a supervisor
 * that looks installed and does nothing, which is worse than no
 * supervisor at all, because `klio doctor` would report it as present.
 *
 * So when we detect we are running from an npx cache, the unit is
 * written to invoke `npx -y @klio-tech/klio@<version>` instead. That is
 * slower (it may hit the network) and pinned to the version that ran
 * init, both of which are acceptable for a check that runs once a
 * minute in the background and must above all keep resolving.
 */
export function resolveKlioCommand(
  argv1: string = process.argv[1] ?? "",
  execPath: string = process.execPath,
  version?: string,
): string[] {
  const fromNpxCache = /[/\\]_npx[/\\]/.test(argv1);

  if (fromNpxCache || argv1 === "") {
    const spec = version ? `@klio-tech/klio@${version}` : "@klio-tech/klio";
    return ["npx", "-y", spec, "proxy", "ensure"];
  }
  return [execPath, argv1, "proxy", "ensure"];
}
